var classes = [
    {
        "name": "App\\Controllers\\Controller",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 1.2,
        "effort": 49.63,
        "level": 0.83,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 34.47,
        "number_operators": 4,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 62.89,
        "mIwoC": 62.89,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "pageRank": 0.4,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\FormController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForms",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSingleForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrivateForms",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "submitForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Controllers\\Controller",
            "parent"
        ],
        "lcom": 2,
        "length": 165,
        "vocabulary": 47,
        "volume": 916.51,
        "difficulty": 14.45,
        "effort": 13241.12,
        "level": 0.07,
        "bugs": 0.31,
        "time": 736,
        "intelligentContent": 63.44,
        "number_operators": 43,
        "number_operands": 122,
        "number_operators_unique": 9,
        "number_operands_unique": 38,
        "cloc": 0,
        "loc": 73,
        "lloc": 73,
        "mi": 37.67,
        "mIwoC": 37.67,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.96,
        "relativeSystemComplexity": 64.96,
        "totalStructuralComplexity": 320,
        "totalDataComplexity": 4.78,
        "totalSystemComplexity": 324.78,
        "pageRank": 0.08,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Mail\\MailController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Controllers\\Mail\\Message"
        ],
        "lcom": 1,
        "length": 25,
        "vocabulary": 10,
        "volume": 83.05,
        "difficulty": 4.29,
        "effort": 355.92,
        "level": 0.23,
        "bugs": 0.03,
        "time": 20,
        "intelligentContent": 19.38,
        "number_operators": 5,
        "number_operands": 20,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 4,
        "loc": 25,
        "lloc": 21,
        "mi": 86.49,
        "mIwoC": 57.45,
        "commentWeight": 29.04,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.7,
        "relativeSystemComplexity": 16.7,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.4,
        "totalSystemComplexity": 33.4,
        "pageRank": 0.08,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\Mail\\Message",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "to",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "subject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "body",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 6,
        "volume": 38.77,
        "difficulty": 1.2,
        "effort": 46.53,
        "level": 0.83,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 32.31,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 3,
        "loc": 24,
        "lloc": 21,
        "mi": 85.94,
        "mIwoC": 59.9,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 6,
        "pageRank": 0.29,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ObjectController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormObjects",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormObjectSQLResult",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatementResults",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controllers\\Controller",
            "parent"
        ],
        "lcom": 2,
        "length": 67,
        "vocabulary": 24,
        "volume": 307.19,
        "difficulty": 5.3,
        "effort": 1628.12,
        "level": 0.19,
        "bugs": 0.1,
        "time": 90,
        "intelligentContent": 57.96,
        "number_operators": 14,
        "number_operands": 53,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 0,
        "loc": 42,
        "lloc": 42,
        "mi": 46.64,
        "mIwoC": 46.64,
        "commentWeight": 0,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 36.54,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 2.14,
        "totalSystemComplexity": 146.14,
        "pageRank": 0.08,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRecoveryHash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkResetPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "changePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 22,
        "ccnMethodMax": 8,
        "externals": [
            "App\\Controllers\\Controller",
            "parent"
        ],
        "lcom": 2,
        "length": 650,
        "vocabulary": 108,
        "volume": 4390.68,
        "difficulty": 22.77,
        "effort": 99987.69,
        "level": 0.04,
        "bugs": 1.46,
        "time": 5555,
        "intelligentContent": 192.8,
        "number_operators": 149,
        "number_operands": 501,
        "number_operators_unique": 9,
        "number_operands_unique": 99,
        "cloc": 12,
        "loc": 284,
        "lloc": 272,
        "mi": 34.08,
        "mIwoC": 18.43,
        "commentWeight": 15.65,
        "kanDefect": 2.04,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 3.41,
        "relativeSystemComplexity": 147.41,
        "totalStructuralComplexity": 1152,
        "totalDataComplexity": 27.31,
        "totalSystemComplexity": 1179.31,
        "pageRank": 0.08,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]